"""Core primitives for Harness Labs."""

from harness_labs.core.attempts import (
    AttemptRunner,
    Executor,
    InvalidAttempt,
    InvalidResult,
    TaskAttempt,
    TaskResult,
)
from harness_labs.core.agent_sessions import (
    TOOL_UNAVAILABLE_REFUSAL,
    AgentSession,
    BackendCapabilities,
    BackendFailure,
    FinalOutput,
    ModelEvent,
    ModelRequest,
    SessionToolExecutor,
    ToolCall,
    ToolResult,
    ToolSpec,
    Usage,
)
from harness_labs.core.backends import ClaudePrintBackend, CodexExecBackend, OmlxBackend, PoemBackend
from harness_labs.graphrun.agent_mixture import (
    BackendSpec,
    UI_PLAYWRIGHT_CAPABILITY,
    UI_PLAYWRIGHT_ROLE,
    WorkerRole,
    build_coordinator_session,
    build_role_profiles,
    parse_backend_spec,
    resolve_backend_spec,
    task_with_artifact_kind,
)
from harness_labs.core.claude_agent_session import ClaudeAgentSession, ClaudeSessionError
from harness_labs.core.claude_task_executor import ClaudeSemanticTaskExecutor
from harness_labs.core.audit import AuditActor, AuditArtifact, AuditError, AuditJournal
from harness_labs.core.composition import (
    ChildAuthorization,
    ChildBatchRequest,
    ChildBatchResult,
    ChildDispatcher,
    ChildEvent,
    ChildRequest,
    ChildRequestDenied,
    ConversationalExecutor,
)
from harness_labs.core.codex_delegation import (
    CodexDelegationError,
    CodexFileReaderExecutor,
    CodexReadOnlyWorktreeExecutor,
)
from harness_labs.core.codex_agent_session import CodexAppServerSession, CodexSessionError
from harness_labs.core.omlx_agent_session import OmlxAgentSession
from harness_labs.core.model_capability_executor import ModelCapabilityExecutor
from harness_labs.core.text_executor import (
    InMemoryReferenceStore,
    TextBackend,
    TextBackendError,
    TextExecutor,
)
from harness_labs.core.controller_commands import (
    COMMAND_PROTOCOL,
    RECEIPT_PROTOCOL,
    CommandActor,
    CommandEnvelope,
    CommandProvenance,
    CommandReceipt,
    KernelEvent,
)
from harness_labs.core.controller_coordinator import CoordinatorLoop
from harness_labs.core.coordinator_dispatcher import (
    CoordinatorDispatchResult,
    CoordinatorDispatcher,
    CoordinatorLaunch,
    CoordinatorSessionFactory,
    DispatchedControllerRunResult,
    resume_dispatched_controller,
    run_dispatched_controller,
)
from harness_labs.core.coordinator_schema import (
    COORDINATOR_SCHEMA_PROTOCOL,
    CoordinatorDispatchSchema,
    CoordinatorSegment,
)
from harness_labs.core.controller_evidence import (
    EvidenceCatalog,
    EvidenceError,
    EvidenceRecord,
)
from harness_labs.core.controller_kernel import (
    ControllerKernel,
    KernelError,
    RunContract,
    RunLimits,
)
from harness_labs.core.controller_live import CodexSemanticTaskExecutor, LiveExecutionError
from harness_labs.core.controller_projection import ControllerQueries, project_run_view
from harness_labs.core.controller_results import (
    SEMANTIC_RESULT_PROTOCOL,
    SemanticResultError,
    SemanticTaskResult,
    semantic_payload,
    validate_semantic_result,
)
from harness_labs.core.controller_run import (
    ControllerRunResult,
    restore_controller_checkpoint,
    resume_controller,
    run_controller,
    run_fixture_spec,
)
from harness_labs.core.controller_scheduler import (
    CapabilityScheduler,
    RoleProfile,
    ScheduledOutcome,
    SchedulingError,
)
from harness_labs.featurerun.feature_run import (
    DeterministicVerificationResult,
    FeatureRunHandoffArtifact,
    FeatureRunResult,
    PlanGraphFeatureRunBinding,
    RecoveryAgent,
    TRANSIENT_RECOVERY_SIGNATURES,
    deterministic_recovery_agent,
    RecoveryContext,
    RecoveryDecision,
    VerificationRepairExecutorFactory,
    run_plan_graph_feature_worktree,
    run_feature_worktree,
)
from harness_labs.plangraph.plan_graph import (
    FEATURE_RUN_REQUEST_PROTOCOL,
    PLAN_GRAPH_PROTOCOL,
    REGISTRATION_PROTOCOL,
    ApprovalEvidence,
    FeatureRunOutcome,
    FeatureRunRequest,
    FunctionalityCommand,
    PathIntent,
    PlanGraph,
    PlanGraphError,
    PlanGraphPlan,
    PlanGraphRegistration,
    PlanGraphResult,
    PlanRun,
    RequiredPath,
    SubprocessFeatureRunLauncher,
    load_registration,
    persist_registration,
    plan_from_mapping,
    plan_from_registration,
    register_plan_graph,
    validate_plan_graph_plan,
    verify_registration,
)
from harness_labs.plangraph.plan_approval import (
    PlanApprovalAdmission,
    PlanApprovalError,
    PreparedApproval,
    ValidatedApproval,
    issue_receipt,
    prepare_approval,
)
from harness_labs.featurerun.review_fix import (
    REVIEW_FIX_RESULT_PROTOCOL,
    REVIEW_LEDGER_PROTOCOL,
    ReviewFixError,
    ReviewFixExecutorFactory,
    ReviewFixLoop,
    ReviewFixPolicy,
    ReviewFixResult,
    ReviewLedger,
)
from harness_labs.core.git_transaction import (
    GitTransactionError,
    GitWorktreeTransaction,
    changed_paths,
    normalize_allowed_paths,
    paths_outside_scope,
    workspace_snapshot,
)
from harness_labs.core.capability_broker import (
    BrokeredCapabilityExecutor,
    CapabilityBroker,
    CapabilityDenied,
    CapabilityPolicy,
    CapabilityReceipt,
    CapabilityRequest,
)
from harness_labs.core.development_policy import (
    DevelopmentPolicy,
    ReviewAssignment,
)
from harness_labs.featurerun.feature_run_policy import (
    standard_feature_run_dispatch_schema,
    standard_feature_run_policy,
    standard_review_continuation_recovery_agent,
)
from harness_labs.core.usage import ModelPrice, build_run_summary, usage_payload

__all__ = [
    "AttemptRunner",
    "CapabilityBroker",
    "BrokeredCapabilityExecutor",
    "CapabilityDenied",
    "CapabilityPolicy",
    "CapabilityReceipt",
    "CapabilityRequest",
    "AuditActor",
    "AuditArtifact",
    "AuditError",
    "AuditJournal",
    "AgentSession",
    "BackendCapabilities",
    "BackendFailure",
    "ChildAuthorization",
    "ChildBatchRequest",
    "ChildBatchResult",
    "ChildDispatcher",
    "ChildEvent",
    "ChildRequest",
    "ChildRequestDenied",
    "ConversationalExecutor",
    "BackendSpec",
    "ClaudePrintBackend",
    "ClaudeAgentSession",
    "ClaudeSemanticTaskExecutor",
    "ClaudeSessionError",
    "CodexExecBackend",
    "CodexDelegationError",
    "CodexFileReaderExecutor",
    "CodexReadOnlyWorktreeExecutor",
    "CodexAppServerSession",
    "CodexSessionError",
    "CodexSemanticTaskExecutor",
    "Executor",
    "DevelopmentPolicy",
    "InvalidAttempt",
    "InvalidResult",
    "InMemoryReferenceStore",
    "FinalOutput",
    "ModelEvent",
    "ModelPrice",
    "ModelRequest",
    "ModelCapabilityExecutor",
    "OmlxBackend",
    "OmlxAgentSession",
    "PoemBackend",
    "TaskAttempt",
    "TaskResult",
    "SessionToolExecutor",
    "TOOL_UNAVAILABLE_REFUSAL",
    "TextBackend",
    "TextBackendError",
    "TextExecutor",
    "ToolCall",
    "ToolResult",
    "ToolSpec",
    "Usage",
    "COMMAND_PROTOCOL",
    "RECEIPT_PROTOCOL",
    "SEMANTIC_RESULT_PROTOCOL",
    "CapabilityScheduler",
    "CommandActor",
    "CommandEnvelope",
    "CommandProvenance",
    "CommandReceipt",
    "ControllerKernel",
    "ControllerQueries",
    "ControllerRunResult",
    "CoordinatorLoop",
    "COORDINATOR_SCHEMA_PROTOCOL",
    "CoordinatorDispatchResult",
    "CoordinatorDispatcher",
    "CoordinatorDispatchSchema",
    "CoordinatorLaunch",
    "CoordinatorSegment",
    "CoordinatorSessionFactory",
    "DispatchedControllerRunResult",
    "DeterministicVerificationResult",
    "FeatureRunHandoffArtifact",
    "EvidenceCatalog",
    "EvidenceError",
    "EvidenceRecord",
    "KernelError",
    "KernelEvent",
    "GitTransactionError",
    "GitWorktreeTransaction",
    "FeatureRunResult",
    "PlanGraphFeatureRunBinding",
    "RecoveryAgent",
    "TRANSIENT_RECOVERY_SIGNATURES",
    "deterministic_recovery_agent",
    "RecoveryContext",
    "RecoveryDecision",
    "FEATURE_RUN_REQUEST_PROTOCOL",
    "REGISTRATION_PROTOCOL",
    "FeatureRunOutcome",
    "FeatureRunRequest",
    "ApprovalEvidence",
    "FunctionalityCommand",
    "PathIntent",
    "PlanApprovalAdmission",
    "PlanApprovalError",
    "PreparedApproval",
    "RequiredPath",
    "ValidatedApproval",
    "PLAN_GRAPH_PROTOCOL",
    "PlanGraph",
    "PlanGraphError",
    "PlanGraphPlan",
    "PlanGraphRegistration",
    "PlanGraphResult",
    "PlanRun",
    "SubprocessFeatureRunLauncher",
    "REVIEW_FIX_RESULT_PROTOCOL",
    "REVIEW_LEDGER_PROTOCOL",
    "ReviewFixError",
    "ReviewFixExecutorFactory",
    "ReviewFixLoop",
    "ReviewFixPolicy",
    "ReviewFixResult",
    "ReviewAssignment",
    "ReviewLedger",
    "LiveExecutionError",
    "RoleProfile",
    "RunContract",
    "RunLimits",
    "ScheduledOutcome",
    "SchedulingError",
    "SemanticResultError",
    "SemanticTaskResult",
    "project_run_view",
    "changed_paths",
    "normalize_allowed_paths",
    "paths_outside_scope",
    "restore_controller_checkpoint",
    "run_controller",
    "run_dispatched_controller",
    "resume_dispatched_controller",
    "run_feature_worktree",
    "run_plan_graph_feature_worktree",
    "load_registration",
    "persist_registration",
    "plan_from_mapping",
    "prepare_approval",
    "issue_receipt",
    "plan_from_registration",
    "register_plan_graph",
    "validate_plan_graph_plan",
    "verify_registration",
    "run_fixture_spec",
    "resume_controller",
    "semantic_payload",
    "validate_semantic_result",
    "VerificationRepairExecutorFactory",
    "workspace_snapshot",
    "build_run_summary",
    "standard_feature_run_dispatch_schema",
    "standard_feature_run_policy",
    "standard_review_continuation_recovery_agent",
    "usage_payload",
    "UI_PLAYWRIGHT_CAPABILITY",
    "UI_PLAYWRIGHT_ROLE",
    "WorkerRole",
    "build_coordinator_session",
    "build_role_profiles",
    "parse_backend_spec",
    "resolve_backend_spec",
    "task_with_artifact_kind",
]
